version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  # api:
  #  build: .
  #  ports:
  #    - "8000:5000"
      
