version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=jMlo89ws!
      - MYSQL_DATABASE=widget
      - MYSQL_USER=widget
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - 8080:8080
  api:
    build: ./app/
    ports:
      - "8000:5000"
      
